"""initial_schema

Revision ID: 654be334a24e
Revises: 
Create Date: 2026-04-16 01:07:05.984722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654be334a24e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('bbox', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attack_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('source_country', sa.String(length=100), nullable=False),
    sa.Column('source_lat', sa.Float(), nullable=False),
    sa.Column('source_lng', sa.Float(), nullable=False),
    sa.Column('dest_ip', sa.String(length=45), nullable=False),
    sa.Column('dest_country', sa.String(length=100), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lng', sa.Float(), nullable=False),
    sa.Column('attack_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_events_attack_type'), 'attack_events', ['attack_type'], unique=False)
    op.create_index(op.f('ix_attack_events_cluster_id'), 'attack_events', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_attack_events_dest_country'), 'attack_events', ['dest_country'], unique=False)
    op.create_index(op.f('ix_attack_events_dest_ip'), 'attack_events', ['dest_ip'], unique=False)
    op.create_index(op.f('ix_attack_events_source_country'), 'attack_events', ['source_country'], unique=False)
    op.create_index(op.f('ix_attack_events_source_ip'), 'attack_events', ['source_ip'], unique=False)
    op.create_index(op.f('ix_attack_events_timestamp'), 'attack_events', ['timestamp'], unique=False)
    op.create_table('country_risk_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('cyber_score', sa.Float(), nullable=False),
    sa.Column('news_score', sa.Float(), nullable=False),
    sa.Column('attack_count_24h', sa.Integer(), nullable=False),
    sa.Column('snapshotted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_risk_snapshots_iso2'), 'country_risk_snapshots', ['iso2'], unique=False)
    op.create_index(op.f('ix_country_risk_snapshots_snapshotted_at'), 'country_risk_snapshots', ['snapshotted_at'], unique=False)
    op.create_table('financial_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('is_real', sa.Boolean(), nullable=False),
    sa.Column('snapshotted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_snapshots_asset_class'), 'financial_snapshots', ['asset_class'], unique=False)
    op.create_index(op.f('ix_financial_snapshots_snapshotted_at'), 'financial_snapshots', ['snapshotted_at'], unique=False)
    op.create_index(op.f('ix_financial_snapshots_symbol'), 'financial_snapshots', ['symbol'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_category'), 'news_items', ['category'], unique=False)
    op.create_index(op.f('ix_news_items_published_at'), 'news_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_items_region'), 'news_items', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_items_region'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_published_at'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_category'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_financial_snapshots_symbol'), table_name='financial_snapshots')
    op.drop_index(op.f('ix_financial_snapshots_snapshotted_at'), table_name='financial_snapshots')
    op.drop_index(op.f('ix_financial_snapshots_asset_class'), table_name='financial_snapshots')
    op.drop_table('financial_snapshots')
    op.drop_index(op.f('ix_country_risk_snapshots_snapshotted_at'), table_name='country_risk_snapshots')
    op.drop_index(op.f('ix_country_risk_snapshots_iso2'), table_name='country_risk_snapshots')
    op.drop_table('country_risk_snapshots')
    op.drop_index(op.f('ix_attack_events_timestamp'), table_name='attack_events')
    op.drop_index(op.f('ix_attack_events_source_ip'), table_name='attack_events')
    op.drop_index(op.f('ix_attack_events_source_country'), table_name='attack_events')
    op.drop_index(op.f('ix_attack_events_dest_ip'), table_name='attack_events')
    op.drop_index(op.f('ix_attack_events_dest_country'), table_name='attack_events')
    op.drop_index(op.f('ix_attack_events_cluster_id'), table_name='attack_events')
    op.drop_index(op.f('ix_attack_events_attack_type'), table_name='attack_events')
    op.drop_table('attack_events')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
